### ISSUE TITLE
Detailed instructions

### ISSUE THREAD

**Issue by Damat7** [code-kotis/barcode-scanner#110]
Super, great demonstration of how the application works.
But, I got a problem when installing on shared hosting, with node.
For a beginner, please post more detailed installation instructions.
Is it possible to launch this application using Passenger? And which file is being launched from the browser.
Thank.

**Comment by Damat7** [comment]
Raw process output:
(node:157323) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
/home/a0463269/domains/aisso.ru/public_html/app/decoder.js:20
self.onmessage = function(imgData) {
^

ReferenceError: self is not defined
    at Object.<anonymous> (/home/a0463269/domains/aisso.ru/public_html/app/decoder.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadApplication (/opt/rh/rh-passenger40/root/usr/share/passenger/helper-scripts/node-loader.js:120:2)
    at setupEnvironment (/opt/rh/rh-passenger40/root/usr/share/passenger/helper-scripts/node-loader.js:91:2)
Error ID
d25241a2
Application root
/home/a0463269/domains/aisso.ru/public_html/app
Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)
production
User and groups
uid=5250(a0463269) gid=5251(a0463269) groups=5251(a0463269),751(customers),753(noperl),994(mem512M) context=system_u:system_r:httpd_t:s0
Environment variables
MANPATH=/opt/rh/rh-nodejs10/root/usr/share/man:/opt/rh/httpd24/root/usr/share/man:
HTTPD=httpd24-httpd
PROFILE=PERSONAL
LIBRARY_PATH=/opt/rh/httpd24/root/usr/lib64
IDLESHUTDOWN=0
X_SCLS= httpd24 rh-nodejs10
GROUP=a0463269
USER=a0463269
LD_LIBRARY_PATH=/opt/rh/rh-nodejs10/root/usr/lib64:/opt/rh/httpd24/root/usr/lib64
BACKEND=NODE10
ARGUMENTS=
PATH=/opt/rh/rh-nodejs10/root/usr/bin:/opt/rh/httpd24/root/usr/bin:/opt/rh/httpd24/root/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
MAXCLIENTS=6
PWD=/home/a0463269/domains/aisso.ru/public_html/app
HTTPD24_HTTPD_SCLS_ENABLED=httpd24 rh-nodejs10
LANG=en_US.UTF-8
NOTIFY_SOCKET=/run/systemd/notify
SHLVL=0
PYTHONPATH=/opt/rh/rh-nodejs10/root/usr/lib/python2.7/site-packages
PKG_CONFIG_PATH=/opt/rh/httpd24/root/usr/lib64/pkgconfig
LISTEN=127.0.0.1:65012
PASSENGER_DEBUG_DIR=/tmp/passenger.spawn-debug.XXXXGr8NFH
LOGNAME=a0463269
SHELL=/bin/bash
HOME=/home/a0463269
IN_PASSENGER=1
PYTHONUNBUFFERED=1
NODE_PATH=/opt/rh/rh-passenger40/root/usr/share/passenger/node
RAILS_ENV=production
RACK_ENV=production
WSGI_ENV=production
NODE_ENV=production
PASSENGER_APP_ENV=production
HTTPS=on
SCRIPT_URI=http://aisso.ru/manifest.json
SERVER_PROTOCOL=HTTP/1.0
SCRIPT_URL=/manifest.json
SERVER_SOFTWARE=Apache/2.4.34
DOCUMENT_ROOT=/home/a0463269/domains/aisso.ru/public_html
SERVER_ADMIN=webmaster@from.sh
QUERY_STRING=
X_DOCROOT=/home/a0463269/domains/aisso.ru/public_html
SERVER_NAME=aisso.ru
REMOTE_PORT=51010
REMOTE_ADDR=127.0.0.1
SERVER_PORT=80
REQUEST_METHOD=GET
SERVER_ADDR=127.0.0.1
REQUEST_URI=/manifest.json
GHOST_NODE_VERSION_CHECK=false
Ulimits
Unknown
System metrics
------------- General -------------
Kernel version    : 3.10.0-1127.13.1.el7.x86_64
Uptime            : 36d 8h 10m 5s
Load averages     : 19.50%, 17.36%, 14.22%
Fork rate         : unknown

------------- CPU -------------
Number of CPUs    :   16
Average CPU usage :  76%  --  61% user,   0% nice,  14% system,  24% idle
  CPU 1           : 100%  --  80% user,   0% nice,  20% system,   0% idle
  CPU 2           : 100%  -- 100% user,   0% nice,   0% system,   0% idle
  CPU 3           :  80%  --  60% user,   0% nice,  20% system,  20% idle
  CPU 4           :  80%  --  40% user,   0% nice,  40% system,  20% idle
  CPU 5           : 100%  -- 100% user,   0% nice,   0% system,   0% idle
  CPU 6           : 100%  -- 100% user,   0% nice,   0% system,   0% idle
  CPU 7           : 100%  -- 100% user,   0% nice,   0% system,   0% idle
  CPU 8           :  80%  --  80% user,   0% nice,   0% system,  20% idle
  CPU 9           :  50%  --  33% user,   0% nice,  17% system,  50% idle
  CPU 10          :  60%  --  20% user,   0% nice,  40% system,  40% idle
  CPU 11          :  25%  --  25% user,   0% nice,   0% system,  75% idle
  CPU 12          :  75%  --  25% user,   0% nice,  50% system,  25% idle
  CPU 13          :  40%  --  20% user,   0% nice,  20% system,  60% idle
  CPU 14          : 100%  -- 100% user,   0% nice,   0% system,   0% idle
  CPU 15          :  20%  --  20% user,   0% nice,   0% system,  80% idle
  CPU 16          : 100%  --  80% user,   0% nice,  20% system,   0% idle
I/O pressure      :   0%
  CPU 1           :   0%
  CPU 2           :   0%
  CPU 3           :   0%
  CPU 4           :   0%
  CPU 5           :   0%
  CPU 6           :   0%
  CPU 7           :   0%
  CPU 8           :   0%
  CPU 9           :   0%
  CPU 10          :   0%
  CPU 11          :   0%
  CPU 12          :   0%
  CPU 13          :   0%
  CPU 14          :   0%
  CPU 15          :   0%
  CPU 16          :   0%
Interference from other VMs:   0%
  CPU 1                    :   0%
  CPU 2                    :   0%
  CPU 3                    :   0%
  CPU 4                    :   0%
  CPU 5                    :   0%
  CPU 6                    :   0%
  CPU 7                    :   0%
  CPU 8                    :   0%
  CPU 9                    :   0%
  CPU 10                   :   0%
  CPU 11                   :   0%
  CPU 12                   :   0%
  CPU 13                   :   0%
  CPU 14                   :   0%
  CPU 15                   :   0%
  CPU 16                   :   0%

------------- Memory -------------
RAM total         : 128434 MB
RAM used          :  77256 MB (60%)
RAM free          :  51177 MB
Swap total        :   6999 MB
Swap used         :   1768 MB (25%)
Swap free         :   5231 MB
Swap in           : unknown
Swap out          : unknown

**Comment by Damat7** [comment]
I figured it out, I close it.
